# --- Main colors ---
background            #16130b
foreground            #e9e2d4

selection_background  #4e462a
selection_foreground  #efe2bc
url_color             #aad0b2

color0                #1e1b13
color1                #ffb4ab
color2                #d2c6a1
color3                #aad0b2
color4                #ddc66e
color5                #93000a
color6                #979080
color7                #e9e2d4
color8                #38352b
color9                #ffb4ab
color10               #d2c6a1
color11               #aad0b2
color12               #ddc66e
color13               #93000a
color14               #4b4739
color15               #cdc6b4

# --- UI ---
active_tab_foreground   #3a3000
active_tab_background   #ddc66e
inactive_tab_foreground #cdc6b4
inactive_tab_background #1e1b13

active_border_color     #ddc66e
inactive_border_color   #38352b
