# --- Main colors ---
background            #19120c
foreground            #efe0d6

selection_background  #5a422e
selection_foreground  #ffdcc3
url_color             #c5cb96

color0                #221a14
color1                #ffb4ab
color2                #e3c0a6
color3                #c5cb96
color4                #ffb77d
color5                #93000a
color6                #9e8e82
color7                #efe0d6
color8                #3c332c
color9                #ffb4ab
color10               #e3c0a6
color11               #c5cb96
color12               #ffb77d
color13               #93000a
color14               #51443b
color15               #d6c3b6

# --- UI ---
active_tab_foreground   #4d2600
active_tab_background   #ffb77d
inactive_tab_foreground #d6c3b6
inactive_tab_background #221a14

active_border_color     #ffb77d
inactive_border_color   #3c332c
